common: &default_settings
  license_key: '<%= ENV["NEW_RELIC_LICENSE_KEY"] %>'
  app_name: <%= ENV["NEW_RELIC_APP_NAME"] %>
  monitor_mode: true
  log_level: info
  browser_monitoring:
      auto_instrument: true

  capture_params: false

  transaction_tracer:
    enabled: true
    transaction_threshold: apdex_f
    record_sql: obfuscated
    stack_trace_threshold: 0.500

  error_collector:
    enabled: true
    capture_source: false
    ignore_errors: "ActionController::RoutingError,Sinatra::NotFound"
